### PR TITLE
Fix ios open in the browser and added setSessionData ability

### LINKED ISSUE #12: Add user's data
I want to add some data for user like the app version and so on

image

I need to use webview javascript method for this?

### LINKED ISSUE #13: crisp in ios
hi , wish you best!
i am using crisp in my aoolication it is ok in android but i have problem in ios, in ios side it opens a browser page and does not behave as a widget

### PR DESCRIPTION
**Pull request by kcrebound**
* Fixed #13 
* Fixed #12

I think `shouldOverrideUrlLoading` is not needed, without it works good on iOS

### CODE REVIEW

**Comment by f2acode** [comment]
@kcrebound Did you test sending a link on the chat? This is the purpose of the `shouldOverrideUrlLoading` function, to avoid leaving the chat and force open the browser in these cases.

**Comment by kcrebound** [comment]
> @kcrebound Did you test sending a link on the chat? This is the purpose of the `shouldOverrideUrlLoading` function, to avoid leaving the chat and force open the browser in these cases.

I will check this, thank you

**Comment by kcrebound** [comment]
> @kcrebound Did you test sending a link on the chat? This is the purpose of the `shouldOverrideUrlLoading` function, to avoid leaving the chat and force open the browser in these cases.

I added a rule to check host, now it works normally. 
Is ok now? what do you think?

**Comment by f2acode** [comment]
@kcrebound The first condition needs to check the `schema` (the pattern or urls are `scheme://host:port/path?query`), so the inner condition needs to be wrap it, something like this will work:

```
if(uri?.host != 'go.crisp.chat'){
    if ([
        "http",
        "https",
        "tel",
        "mailto",
        "file",
        "chrome",
        "data",
        "javascript",
        "about"
        ].contains(uri?.schema)) {
        if (await canLaunch(url)) {
            await launch(url);

            return NavigationActionPolicy.CANCEL;
        }
    }
}
```

**Comment by kcrebound** [comment]
> Can you check? After that it will be ready 😄

Fixed, and I added `setSessionData` ability

image

**Comment by f2acode** [comment]
> > Can you check? After that it will be ready smile
> 
> Fixed, and I added `setSessionData` ability
> 
> image

Really great! Thank you!

**Pull request merged**
